---
title: Prof. Dr.
surname: André Calero Valdez
position: "Human-Computer Interaction and Usable Safety Engineering"
address: "Institute of Multimedia and Interactive Systems, University of Lübeck"
#phone: +1 22 3333 4444
www: calerovaldez.com
email: "andre.calerovaldez@uni-luebeck.de"
profilepic: "`r paste0('..',stringr::str_remove(here::here('data','photo.jpeg'), here::here()))`"
twitter: sumidu
github: sumidu
#linkedin: mariecurie
date: "`r format(Sys.time(), '%B %Y')`"
classoption: "sans"
header-includes:
  - \usepackage[utf8]{inputenc}
  - \usepackage[T1]{fontenc}
  - \usepackage[sfdefault,scaled=.85]{FiraSans}
  - \usepackage{eurosym}
  - \usepackage{csquotes}
output: vitae::moderncv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tidyverse)
library(here)
source(here::here("R", "getdata.R"))

library(DBI)
library(RSQLite)
library(tidyverse)

db <- dbConnect(RSQLite::SQLite(), here("data", "my_data.db"))
jobs <- tbl(db, "jobs") |> collect()

dbDisconnect(db)

```

```{r data_loading, include=FALSE}
lang <- "de"
# Data Loading ----
#jobs <- load_jobs(lang)
#teaching <- load_teaching(lang)
#service <- load_services(lang)
#reviews <- load_reviews(lang)
#memberships <- load_memberships(lang)
#presentations <- load_presentations(lang)
#grants <- load_grants(lang)
#software <- load_software(lang)

scholar_profile <- get_scholar_profile(update_pubs = TRUE)
#rgate <- get_research_gate_score()
```



# About me

```{r about_me, results="asis"}
pd_df <- tribble(~meta, ~input,
              "Name", "Prof. Dr. phil. André Calero Valdez", 
              #"Geburtsdatum","22. Januar 1981",
              #"Familienstand", "verheiratet mit Eva-Maria Peters (Studienrätin)",
              #"Kinder", "Tochter (6 Jahre alt), Sohn (2 Jahre)",
              #"Adresse", "Poelring 5",
              #"", "23560 Lübeck",
              "Email", "andrecalerovaldez@gmail.com",
              "www", "www.calerovaldez.com",
              "Languages", "German (mother tongue)",
              "",         "English (fluent)",
              "",         "Spanish (basic knowledge)"
              )

vitae::brief_entries(pd_df, when = meta, what = input, with = "") 
```

\vspace{1em}

## Academic metrics

```{r metrics, results="asis"}
metrics_df <- tribble(~meta, ~input,
              "Citations", scholar_profile$total_cites %>% as.character(),
              "h-Index", scholar_profile$h_index %>% as.character(),
              "i10-Index", scholar_profile$i10_index %>% as.character(),
              "Acquired Third-Party Funding", "approx. 3 Mio \\euro",
              )

brief_entries(metrics_df, when = meta, what = input, .protect = F)
```

# Berufliche Erfahrung

```{r research}

jobs %>% 
  mutate(startyear = as.character(year(start))) |> 
  mutate(endyear = as.character(year(end))) |>
  mutate(endyear = ifelse(active == 1, "heute", endyear)) |>
  rowwise() |>
  mutate(desc_list = as.vector((str_split(paste0(description,""), ";")))) |> 
  mutate(when = glue::glue("{startyear} - {endyear}")) %>%
  arrange(desc(start)) %>% 
  detailed_entries(
    what = name,
    when = when,
    with = with,
    where = location,
    why = desc_list
  )
```



# Some stuff about me
 * I poisoned myself doing research.
 * I was the first woman to win a Nobel prize
 * I was the first person and only woman to win a Nobel prize in two different sciences.

# Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Informal studies", "1889-91", "Flying University", "Warsaw, Poland",
  "Master of Physics", "1893", "Sorbonne Université", "Paris, France",
  "Master of Mathematics", "1894", "Sorbonne Université", "Paris, France"
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

# Nobel Prizes

```{r}
tribble(
  ~Year, ~Type, ~Desc,
  1903, "Physics", "Awarded for her work on radioactivity with Pierre Curie and Henri Becquerel",
  1911, "Chemistry", "Awarded for the discovery of radium and polonium"
) %>% 
  brief_entries(
    glue::glue("Nobel Prize in {Type}"),
    Year, 
    Desc
  )
```

# Publications

```{r}
library(dplyr)
knitr::write_bib(c("vitae", "tibble"), "packages.bib")

bibliography_entries("packages.bib") %>%
  arrange(desc(author$family), issued)
```

