on:
  push:
    branches: master
  #schedule:
  #  - cron: '0 0 * * MON'
    
name: Render cv

jobs:
  render:
    name: Render cv to PDF
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-renv@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install required packages
        run: |
          install.packages("rmarkdown")
          install.packages("vitae")
        shell: Rscript {0}
      - name: Install tinytex
        run: |
          install.packages("tinytex")
          tinytex::install_tinytex()
        shell: Rscript {0}
      - name: Render cv
        run: Rscript -e 'rmarkdown::render("cv/cv.Rmd", output_format = "pdf_document")'
      - name: Commit results
        run: |
          git commit cv/cv.pdf -m 'Re-build cv.Rmd' || echo "No changes to commit"
          git push origin || echo "No changes to commit"