on:
  push:
    branches: master

name: Render README

jobs:
  render:
    name: Render README
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install rmarkdown
        run: |
          install.packages("rmarkdown")
          install.packages("vitae")
        shell: Rscript {0}
      - name: Render README
        run: Rscript -e 'rmarkdown::render("cv.Rmd", output_format = "pdf_document")'
      - name: Commit results
        run: |
          git commit cv.pdf -m 'Re-build cv.Rmd' || echo "No changes to commit"
          git push origin || echo "No changes to commit"